program: main.py
name: CLUSTER_mask_IP_ISSN
method: bayes
metric:
  goal: maximize
  name: mean_best_test_accs
parameters:
  method:
    values: ['inv_scale_space']
  dataset:
    values: ['CLUSTER']
  lr:
    min: 0.0001
    max: 0.01
  wd:
    min: 0.0
    max: 0.0001
  cglsIter:
    values: [8, 16, 32]
  solveIter:
    values: [8,16,32]
  classify:
    values: [1]
  task:
    values: [mask]
  layers:
    values: [8,16]
  channels:
    values: [32,64,128]
  train_batch_size:
    values: [32, 50, 64]
  regnet:
    values: [hyper]  # when method is 'pgd' this choice doesn't matter - see code
  epochs:
    values: [250]
  datapath:
    values: ['/data/shahriar/datasets/GNN/']
  cluster:
    values: [1]
  rnfPE:
    values: [0,1]
  mask_per_class_budget:
    values: [4]
  use_meta_data:
    values: [1]
  max_patience:
    values: [35]
  #optimizer:
  #  values: ["adam", "sgd"]
