program: main.py
name: CLUSTER_deblurring_IP
method: bayes
metric:
  goal: maximize
  name: best_test_acc
parameters:
  dataset:
    values: ['CLUSTER']
  lr:
    values: [1e-3]
  wd:
    min: 0.0
    max: 0.0001
  cglsIter:
    values: [8, 20, 30]
  solveIter:
    values: [10,15,20]
  classify:
    values: [1]
  task:
    values: [deblur]
  layers:
    values: [8,16]
  channels:
    values: [32,64,70]
  train_batch_size:
    values: [32, 50]
  regnet:
    values: [LA]
  epochs:
    values: [5]
  datapath:
    values: ['/data/shahriar/datasets/GNN/']
  cluster:
    values: [0]
  rnfPE:
    values: [0,1,2]
  #optimizer:
  #  values: ["adam", "sgd"]
