program: main.py
name: CPOX_deblurring_IP_blurCount4
method: bayes
metric:
  goal: minimize
  name: best_test_loss
parameters:
  method:
    values: ['drip']
  dataset:
    values: ['CPOX']
  lr:
    min: 0.0001
    max: 0.01
  wd:
    min: 0.0
    max: 0.0001
  cglsIter:
    values: [8, 16, 32]
  solveIter:
    values: [8,16,32]
  classify:
    values: [0]
  task:
    values: [deblur]
  layers:
    values: [8,16,32,64]
  channels:
    values: [32,64,128]
  train_batch_size:
    values: [16, 32, 64]
  regnet:
    values: [LA]
  epochs:
    values: [100]
  datapath:
    values: ['/data/shahriar/datasets/GNN/']
  cluster:
    values: [0]
  rnfPE:
    values: [0,1]
  blur_count:
    values: [4]
  #optimizer:
  #  values: ["adam", "sgd"]
