program: main.py
name: METRLA_pathlength_8_IP
method: bayes
metric:
  goal: minimize
  name: best_test_loss
parameters:
  method:
    values: ['drip']
  dataset:
    values: ['METRLA']
  lr:
    min: 0.0001
    max: 0.01
  wd:
    min: 0.0
    max: 0.0001
  cglsIter:
    values: [8]
  solveIter:
    values: [1,2,4]
  classify:
    values: [0]
  task:
    values: [path]
  layers:
    values: [2,4,8]
  channels:
    values: [32,64,128]
  batch_size:
    values: [32, 64, 128]
  regnet:
    values: [hyper]
  epochs:
    values: [500]
  datapath:
    values: ['/home/eliasof/inverseProblems/data/']
  cluster:
    values: [1]
  rnfPE:
    values: [0,1]
  pathLength:
    values: [8]
  #optimizer:
  #  values: ["adam", "sgd"]
